env:
  browser: true,
  node: true
extends:
  - 'airbnb-base'
  - 'prettier'
plugins:
  - import
parserOptions:
  ecmaVersion: 2020
rules:
  import/extensions: 0
  linebreak-style: ['error', 'unix']
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
