env:
  browser: true,
  node: true,
  jest: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'prettier'
plugins:
  - import
  - jest
parser: 'babel-eslint'
rules:
  import/extensions: 0
  linebreak-style: ['error', 'unix']
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
  no-underscore-dangle: 0
